name: Update BellSoft Liberica NIK

on:
  schedule:
    - cron: 0 15 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for BellSoft Liberica NIK"
    strategy:
      fail-fast: false
      matrix:
        include:
          - distribution-version: 23
            java-version: 17
          - distribution-version: 23
            java-version: 24
          - distribution-version: 24
            java-version: 23
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 24
          cache: 'maven'
      - name: Run bellsoft-liberica
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=liberica_native --foojay.distribution.version=${{ matrix.distribution-version }} --foojay.java.version=${{ matrix.java-version }} --foojay.java.release-status=ga"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
