name: Update IBM Semeru

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for IBM Semeru"
    strategy:
      fail-fast: false
      matrix:
        java-version: [ 8, 11, 17, 18, 19 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Run ibm semeru
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=semeru --foojay.distribution.version=${{ matrix.java-version }} --foojay.java.release-status=ga"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
