name: Update GraalVM

on:
  schedule:
    - cron: 0 5 * * 1-5
  workflow_dispatch:

jobs:
  run:
    name: "Run Java Migration for GraalVM"
    strategy:
      fail-fast: false
      matrix:
        java-distribution: [ graalvm_ce11, graalvm_ce17]
        distribution-version: [ 21, 22 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Run graalvm
        run: ./mvnw spring-boot:run -Dspring-boot.run.arguments="--foojay.java.distribution=${{ matrix.java-distribution }} --foojay.distribution.version=${{ matrix.distribution-version }} --foojay.java.release-status=ga"
        env:
          SDKMAN_RELEASE_CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          SDKMAN_RELEASE_CONSUMER_TOKEN: ${{ secrets.CONSUMER_TOKEN }}
